package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Clazz generated by hbm2java
 */
public class Clazz implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Integer gid;
	private Date createTime;
	private List<Groups> groupsList = new ArrayList<Groups>();// 班级分组
	private Integer sid;
	private String gname;
	
	private List<ExamScores> avgRankList;// 领导成绩分析的班级平均分排名

	public Clazz() {
	}

	public Clazz(String name, Integer gid, Date createTime) {
		this.name = name;
		this.gid = gid;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getSid() {
		return sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getGname() {
		return gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public List<Groups> getGroupsList() {
		return groupsList;
	}

	public void setGroupsList(List<Groups> groupsList) {
		this.groupsList = groupsList;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public List<ExamScores> getAvgRankList() {
		return avgRankList;
	}

	public void setAvgRankList(List<ExamScores> avgRankList) {
		this.avgRankList = avgRankList;
	}

}
