package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

/**
 * GroupsType generated by hbm2java
 */
public class GroupsType implements java.io.Serializable {

	private Integer id;
	private String name;

	public GroupsType() {
	}

	public GroupsType(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
