package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

/**
 * Module generated by hbm2java
 */
public class Module implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer root;
	private String url;
	private String remarks;
	private String menu;
	private Integer isVisible;

	public Module() {
	}

	public Module(String name, Integer root, String url, String remarks,
			Integer isVisible) {
		this.name = name;
		this.root = root;
		this.url = url;
		this.remarks = remarks;
		this.isVisible = isVisible;
	}

	public String getMenu() {
		return menu;
	}

	public void setMenu(String menu) {
		this.menu = menu;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getRoot() {
		return this.root;
	}

	public void setRoot(Integer root) {
		this.root = root;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getIsVisible() {
		return this.isVisible;
	}

	public void setIsVisible(Integer isVisible) {
		this.isVisible = isVisible;
	}

}
