package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * OnlineUser generated by hbm2java
 */
public class OnlineUser implements java.io.Serializable {

	private Integer id;
	private Date loginTime;
	private Integer uid;
	private Date lastTime;

	private String ip;	
	private String nikeName;

	public OnlineUser() {
	}

	public OnlineUser(Date loginTime, Integer uid, Date lastTime) {
		this.loginTime = loginTime;
		this.uid = uid;
		this.lastTime = lastTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Date getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}


	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getNikeName() {
		return nikeName;
	}

	public void setNikeName(String nikeName) {
		this.nikeName = nikeName;
	}

}
