package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

/**
 * RoleModule generated by hbm2java
 */
public class RoleModule implements java.io.Serializable {

	private Integer id;
	private Integer mid;
	private Integer rid;

	public RoleModule() {
	}

	public RoleModule(Integer mid, Integer rid) {
		this.mid = mid;
		this.rid = rid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getMid() {
		return this.mid;
	}

	public void setMid(Integer mid) {
		this.mid = mid;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

}
