package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.List;

/**
 * Exam generated by hbm2java
 */
public class Exam implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date examTime;
	private Integer uid;
	private Integer gid;
	private Date createTime;
	
	private List<Subjects> subjectsList;
	private List<ExamRowNum> examRowNumList;
	
	public Exam() {
	}

	public Exam(String name, Date examTime, Integer uid, Integer gid,
			Date createTime) {
		this.name = name;
		this.examTime = examTime;
		this.uid = uid;
		this.gid = gid;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getExamTime() {
		return this.examTime;
	}

	public void setExamTime(Date examTime) {
		this.examTime = examTime;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public List<Subjects> getSubjectsList() {
		return subjectsList;
	}

	public void setSubjectsList(List<Subjects> subjectsList) {
		this.subjectsList = subjectsList;
	}

	public List<ExamRowNum> getExamRowNumList() {
		return examRowNumList;
	}

	public void setExamRowNumList(List<ExamRowNum> examRowNumList) {
		this.examRowNumList = examRowNumList;
	}
}
