package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * ExamSubject generated by hbm2java
 */
public class ExamSubject implements java.io.Serializable {

	private Integer id;
	private Integer eid;
	private Integer subjects;
	private Integer total;
	private Date createTime;
	
	private String sname;//学科名称

	public ExamSubject() {
	}

	public ExamSubject(Integer eid, Integer subjects, Integer total,
			Date createTime) {
		this.eid = eid;
		this.subjects = subjects;
		this.total = total;
		this.createTime = createTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEid() {
		return this.eid;
	}

	public void setEid(Integer eid) {
		this.eid = eid;
	}

	public Integer getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Integer subjects) {
		this.subjects = subjects;
	}

	public Integer getTotal() {
		return this.total;
	}

	public void setTotal(Integer total) {
		this.total = total;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
