package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

import java.util.List;

/**
 * 临时类型 短信统计 Exam generated by hbm2java
 */
public class MessageStatistics implements java.io.Serializable {

	private Integer id;
	private String name;// 用户姓名nikeName
	private Integer sendCount;// 接受短信的数量
	private List<MessageType> messageTypeList;// 发送短信的数量，分不同的短信类型

	public MessageStatistics() {
	}

	public MessageStatistics(String name, List<Message> messageList) {
		this.name = name;
		// this.List<Message> = messageList;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSendCount() {
		return sendCount;
	}

	public void setSendCount(Integer sendCount) {
		this.sendCount = sendCount;
	}

	public List<MessageType> getMessageTypeList() {
		return messageTypeList;
	}

	public void setMessageTypeList(List<MessageType> messageTypeList) {
		this.messageTypeList = messageTypeList;
	}

}
