package com.snssly.sms.entity;

// Generated 2010-12-24 16:34:07 by Hibernate Tools 3.2.4.GA

/**
 * Subjects generated by hbm2java
 */
public class Subjects implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer uid;

	private Integer esid;
	private Integer ecsid;

	private boolean isChecked;// 是否选择中

	public Subjects() {
	}

	public Subjects(String name, Integer uid) {
		this.name = name;
		this.uid = uid;
	}

	public boolean isChecked() {
		return isChecked;
	}

	public void setChecked(boolean isChecked) {
		this.isChecked = isChecked;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getEsid() {
		return esid;
	}

	public void setEsid(Integer esid) {
		this.esid = esid;
	}

	public Integer getEcsid() {
		return ecsid;
	}

	public void setEcsid(Integer ecsid) {
		this.ecsid = ecsid;
	}

}
